// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA97U6Sk-_VygRJY8wlZmcSyh4n3zz5sgc',
    appId: '1:1098516869848:web:ba66e2df4f084fe50a9dad',
    messagingSenderId: '1098516869848',
    projectId: 'nest-a65ca',
    authDomain: 'nest-a65ca.firebaseapp.com',
    storageBucket: 'nest-a65ca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAopTi8QIl9ayvcB2fhF3E0MthwH_Zq_gw',
    appId: '1:1098516869848:android:1aceea45ba88cdd50a9dad',
    messagingSenderId: '1098516869848',
    projectId: 'nest-a65ca',
    storageBucket: 'nest-a65ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHorFH7KUj1Ibq2NGyYBLHKEvdXulfdII',
    appId: '1:1098516869848:ios:b0ab4ccae6b35a820a9dad',
    messagingSenderId: '1098516869848',
    projectId: 'nest-a65ca',
    storageBucket: 'nest-a65ca.firebasestorage.app',
    iosBundleId: 'com.example.securenest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHorFH7KUj1Ibq2NGyYBLHKEvdXulfdII',
    appId: '1:1098516869848:ios:b0ab4ccae6b35a820a9dad',
    messagingSenderId: '1098516869848',
    projectId: 'nest-a65ca',
    storageBucket: 'nest-a65ca.firebasestorage.app',
    iosBundleId: 'com.example.securenest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA97U6Sk-_VygRJY8wlZmcSyh4n3zz5sgc',
    appId: '1:1098516869848:web:d8d452c1550e664b0a9dad',
    messagingSenderId: '1098516869848',
    projectId: 'nest-a65ca',
    authDomain: 'nest-a65ca.firebaseapp.com',
    storageBucket: 'nest-a65ca.firebasestorage.app',
  );

}